name: invokeai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip=22.2.2
  - numpy=1.23.3
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pytorch=1.12.1
  - cudatoolkit=11.6
  - pip:
    - albumentations==0.4.3
    - diffusers==0.6.0
    - einops==0.3.0
    - eventlet
    - flask==2.1.3
    - flask_cors==3.0.10
    - flask_socketio==5.3.0
    - getpass_asterisk
    - gfpgan==1.3.8
    - imageio-ffmpeg==0.4.2
    - imageio==2.9.0
    - kornia==0.6.0
    - omegaconf==2.2.3
    - opencv-python==4.5.5.64
    - picklescan
    - pillow==9.2.0
    - pudb==2019.2
    - pyreadline3
    - pytorch-lightning==1.7.7
    - realesrgan
    - send2trash==1.8.0
    - streamlit==1.12.0
    - taming-transformers-rom1504
    - test-tube>=0.7.5
    - torch-fidelity==0.3.0
    - torchmetrics==0.7.0
    - transformers==4.21.3
    - k-diffusion @ https://github.com/Birch-san/k-diffusion/archive/refs/tags/v0.0.10.zip
    - pypatchmatch @ https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.5.zip
    - clipseg @ https://github.com/timojl/clipseg/archive/a5dc13f3649ce67d58505401ce7a7dd25601ffba.zip
    - -e .
