
name: invokeai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.2
  - pytorch=1.13.1
  - torchvision=0.14.1

  - albumentations
  - diffusers=0.10.*
  - einops
  - eventlet
  - grpcio=1.46
  - flask=2.1.3
  - flask-socketio=5.3.0
  - flask-cors=3.0.10
  - huggingface_hub
  - imageio
  - imageio-ffmpeg
  - kornia
  - nomkl
  - numpy
  - omegaconf
  - pillow
  - pudb
  - protobuf
  - py-opencv
  - pytorch-lightning=1.7.7
  - requests=2.25.1
  - scikit-image=0.18.3
  - send2trash
  - streamlit
  - torchmetrics
  - torch-fidelity
  - transformers=4.24
  - pip:
      - getpass_asterisk
      - gfpgan==1.3.8
      - picklescan
      - pyreadline3
      - realesrgan
      - taming-transformers-rom1504
      - test-tube>=0.7.5
      - k-diffusion @ https://github.com/Birch-san/k-diffusion/archive/refs/tags/v0.0.10.zip
      - pypatchmatch @ https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.5.zip
      - clipseg @ https://github.com/timojl/clipseg/archive/a5dc13f3649ce67d58505401ce7a7dd25601ffba.zip
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
