name: invokeai
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip>=22.2
  - pytorch=1.12.1
  - torchvision=0.13.1

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```

  - eventlet
  - grpcio
  - huggingface_hub
  - imageio
  - ffmpeg
  - mpmath=1.2
  - numpy
  - protobuf=3.*
  - requests==2.*
  - scikit-image
  - scipy
  - streamlit
  - sympy
  - send2trash
  - transformers
  - pip:
      - albumentations
      - diffusers==0.10.*
      - einops
      - facexlib
      - flask==2.1.3
      - flask-cors==3.0.10
      - flask-socketio==5.3.0
      - flaskwebgui==1.0.3
      - getpass_asterisk
      - kornia
      - omegaconf
      - picklescan
      - pudb
      - pytorch-lightning==1.7.7
      - realesrgan
      - test-tube>=0.7.5
      - torchmetrics
      - torch-fidelity
      - https://github.com/openai/CLIP/archive/eaa22acb90a5876642d0507623e859909230a52d.zip#egg=clip
      - https://github.com/Birch-san/k-diffusion/archive/refs/heads/mps.zip#egg=k-diffusion
      - https://github.com/invoke-ai/clipseg/archive/relaxed-python-requirement.zip#egg=clipseg
      - https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.5.zip#egg=pypatchmatch
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
