name: invokeai
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip>=22.2
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pytorch-lightning==1.7.7
  - torchmetrics
  - torch-fidelity

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```

  - albumentations
  - diffusers=0.10.*
  - einops
  - eventlet
  - flask=2.1.*
  - flask-cors=3.0.*
  - flask-socketio=5.3.*
  - flaskwebgui==1.0.3
  - grpcio
  - huggingface_hub
  - imageio
  - imageio-ffmpeg=0.4
  - imgaug=0.4
  - kornia=0.6
  - mpmath=1.2
  - numpy
  - omegaconf
  - openh264=2.3
  - pudb
  - protobuf=3.20.*
  - opencv
  - requests=2.25.*
  - scikit-image>=0.19
  - scipy=1.9
  - streamlit=1.12
  - sympy=1.10
  - send2trash=1.8
  - tensorboard=2.10
  - transformers=4.24
  - pip:
      - facexlib
      - getpass_asterisk
      - picklescan
      - realesrgan
      - taming-transformers-rom1504
      - test-tube==0.7.5
      - https://github.com/openai/CLIP/archive/eaa22acb90a5876642d0507623e859909230a52d.zip#egg=clip
      - https://github.com/Birch-san/k-diffusion/archive/refs/heads/mps.zip#egg=k-diffusion
      - https://github.com/invoke-ai/clipseg/archive/relaxed-python-requirement.zip#egg=clipseg
      - https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.5.zip#egg=pypatchmatch
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
