name: invokeai
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.*
  - pip>=22.2
  - pytorch=1.12.*
  - torchvision=0.13.*
  - albumentations=1.3.*
  - diffusers=0.10.*
  - eventlet=0.33.*
  - einops=0.6.*
  - flask=2.2.*
  - flask-socketio=5.3.*
  - flask-cors=3.0.*
  - grpcio=1.47.*
  - huggingface_hub=0.10.*
  - imageio=2.22.*
  - imageio-ffmpeg=0.4.*
  - kornia=0.6.*
  - numpy=1.23.*
  - omegaconf=2.3.*
  - pudb=2019.*
  - py-opencv=4.6.*
  - pytorch-lightning=1.7.*
  - protobuf=3.20.*
  - readline=8.1.*
  - requests=2.28.*
  - scipy=1.9.*
  - streamlit=1.16.*
  - sympy=1.11.*
  - send2trash=1.8.*
  - torch-fidelity=0.3.*
  - transformers=4.*
  - pip:
      - facexlib
      - flaskwebgui==1.0.*
      - getpass_asterisk
      - gfpgan==1.3.*
      - picklescan
      - realesrgan
      - test-tube>=0.7.5
      - https://github.com/Birch-san/k-diffusion/archive/refs/tags/v0.0.10.zip#egg=k-diffusion
      - https://github.com/invoke-ai/clipseg/archive/relaxed-python-requirement.zip#egg=clipseg
      - https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.5.zip#egg=pypatchmatch
      - https://github.com/openai/CLIP/archive/eaa22acb90a5876642d0507623e859909230a52d.zip#egg=clip
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
