name: build container image
on:
  push:
    branches:
      - 'main'
      - 'dev/ci/docker/*'
    tags:
      - 'v*.*.*'

jobs:
  docker:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - amd
          - cuda
          - cpu
        include:
          - flavor: amd
            pip-extra-index-url: 'https://download.pytorch.org/whl/rocm5.2'
            dockerfile: docker-build/Dockerfile
            platforms: linux/amd64,linux/arm64
          - flavor: cuda
            pip-extra-index-url: ''
            dockerfile: docker-build/Dockerfile
            platforms: linux/amd64,linux/arm64
          - flavor: cpu
            pip-extra-index-url: 'https://download.pytorch.org/whl/cpu'
            dockerfile: docker-build/Dockerfile
            platforms: linux/amd64,linux/arm64
    runs-on: ubuntu-latest
    name: ${{ matrix.flavor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavor: |
            latest=auto
            suffix='-${{ matrix.flavor }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: PIP_EXTRA_INDEX_URL=${{ matrix.pip-extra-index-url }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
