# Building the Image without pushing to confirm it is still buildable
# confirum functionality would unfortunately need way more resources
name: build container image
on:
  push:
    branches:
      - 'main'
      - 'development'

jobs:
  pre_job:
    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/docs/**"]'
          do_not_skip: '["pull_request"]'

  docker:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        include:
          - arch: x86_64
            conda-env-file: environment-lin-cuda.yml
          - arch: aarch64
            conda-env-file: environment-lin-aarch64.yml
    runs-on: ubuntu-latest
    name: ${{ matrix.arch }}
    steps:
      - name: prepare docker-tag
        env:
          repository: ${{ github.repository }}
        run: echo "dockertag=${repository,,}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker-build/Dockerfile
          platforms: Linux/${{ matrix.arch }}
          push: false
          tags: ${{ env.dockertag }}:${{ matrix.arch }}
          build-args: |
            conda_env_file=${{ matrix.conda-env-file }}
            conda_version=py39_4.12.0-Linux-${{ matrix.arch }}
            invokeai_git=${{ github.repository }}
            invokeai_branch=${{ github.ref_name }}
