name: Test invoke.py
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types:
      - 'ready_for_review'
      - 'opened'
      - 'synchronize'
      - 'converted_to_draft'

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

jobs:
  fail_if_pull_request_is_draft:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-22.04
    steps:
    - name: Fails in order to indicate that pull request needs to be marked as ready to review and unit tests workflow needs to pass.
      run: exit 1

  matrix:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        environment-yaml:
          - environment-lin-amd.yml
          - environment-lin-cuda.yml
          - environment-mac.yml
          - environment-win-cuda.yml
        include:
          - environment-yaml: environment-lin-amd.yml
            os: ubuntu-22.04
            curl-command: curl
            github-env: $GITHUB_ENV
            default-shell: bash -l {0}
          - environment-yaml: environment-lin-cuda.yml
            os: ubuntu-22.04
            curl-command: curl
            github-env: $GITHUB_ENV
            default-shell: bash -l {0}
          - environment-yaml: environment-mac.yml
            os: macos-12
            curl-command: curl
            github-env: $GITHUB_ENV
            default-shell: bash -l {0}
          - environment-yaml: environment-win-cuda.yml
            os: windows-2022
            curl-command: curl.exe
            github-env: $env:GITHUB_ENV
            default-shell: pwsh
    name: ${{ matrix.environment-yaml }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CONDA_ENV_NAME: invokeai
      INVOKEAI_ROOT: '${{ github.workspace }}/invokeai'
    defaults:
      run:
        shell: ${{ matrix.default-shell }}
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v3

      # - name: create models.yaml from example
      #   run: |
      #     mkdir -p ${{ env.INVOKEAI_ROOT }}/configs
      #     cp configs/models.yaml.example ${{ env.INVOKEAI_ROOT }}/configs/models.yaml

      - name: create environment.yml
        run: cp "environments-and-requirements/${{ matrix.environment-yaml }}" environment.yml

      - name: Activate Conda Env
        id: activate-conda-env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.CONDA_ENV_NAME }}
          environment-file: environment.yml
          miniconda-version: latest

      - name: set test prompt to main branch validation
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "TEST_PROMPTS=tests/preflight_prompts.txt" >> ${{ matrix.github-env }}

      - name: set test prompt to development branch validation
        if: ${{ github.ref == 'refs/heads/development' }}
        run: echo "TEST_PROMPTS=tests/dev_prompts.txt" >> ${{ matrix.github-env }}

      - name: set test prompt to Pull Request validation
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/development' }}
        run: echo "TEST_PROMPTS=tests/validate_pr_prompt.txt" >> ${{ matrix.github-env }}

      - name: run configure_invokeai.py
        id: run-preload-models
        run: |
          python scripts/configure_invokeai.py --yes

      - name: cat invokeai.init
        id: cat-invokeai
        run: cat ${{ env.INVOKEAI_ROOT }}/invokeai.init

      - name: Run the tests
        id: run-tests
        if: matrix.os != 'windows-2022'
        run: |
          time python scripts/invoke.py \
            --no-patchmatch \
            --no-nsfw_checker \
            --from_file ${{ env.TEST_PROMPTS }}

      - name: export conda env
        id: export-conda-env
        if: matrix.os != 'windows-2022'
        run: |
          mkdir -p outputs/img-samples
          conda env export --name ${{ env.CONDA_ENV_NAME }} > ${{ env.INVOKEAI_ROOT }}/outputs/environment-${{ runner.os }}-${{ runner.arch }}.yml

      - name: Archive results
        if: matrix.os != 'windows-2022'
        id: archive-results
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ matrix.requirements-file }}_${{ matrix.python-version }}
          path: ${{ env.INVOKEAI_ROOT }}/outputs
