name: Test invoke.py
on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'add-test-workflows'
  pull_request:
    branches:
      - 'main'
      - 'development'

jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-12
          - windows-latest
        include:
          - os: ubuntu-latest
            installer-zip: InvokeAI-linux.zip
            installer: install.sh
          - os: macOS-12
            installer-zip: InvokeAI-mac.zip
            installer: install.sh
          - os: windows-latest
            installer-zip: InvokeAI-windows.zip
            installer: install.bat
    name: ${{ matrix.installer }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: download installer
        run: curl -o installer.zip -L https://github.com/invoke-ai/InvokeAI/releases/latest/download/${{ matrix.installer }}

      - name: unpack installer
        run: unzip installer.zip

      - name: run installer
        run: ${{ matrix.installer }}
