trigger:
  branches:
    include:
      - dev/ci/*

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: pip install  --use-pep517 --editable=".[test]"
    displayName: 'Install InvokeAI'

  - script: pytest --junitxml=junit/test-results-$(python.version).xml
    displayName: 'run pytest'

  - task: PublishTestResults@1
    condition: succeededOrFailed()
    inputs:
      testRunner: 'JUnit'
      testResultsFiles: '$(Build.SourcesDirectory)/**/test-*.xml'

  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage.xml'
      reportDirectory: $(Build.SourcesDirectory)/htmlcov
